In [1]:
from numpy import random

In [4]:
x= random.randint(100)
print(x)

79


In [5]:
y= random.randint(100,size=5)
print(y)

[67 56 40 23 88]


In [6]:
z= random.randint(100,size=(3,4))
print(z)

[[42 87 88 73]
 [10 91 30 27]
 [ 5 91 73 70]]


In [8]:
a = random.rand()
print(a)

0.5350673635476288


In [9]:
b= random.rand(5)
print(b)

[0.13550317 0.3285272  0.79460414 0.08039839 0.98664697]


In [10]:
c = random.rand(3,4)
print(c)

[[0.52047665 0.08069409 0.27407841 0.25185526]
 [0.52719137 0.72459951 0.72689804 0.05828436]
 [0.56236765 0.38180306 0.62054856 0.60170324]]


In [12]:
p = random.choice([1,3,5,7])
print(p)

5


In [13]:
q = random.choice([1,3,5,7],size=5)
print(q)

[3 1 7 5 1]


In [14]:
r = random.choice([1,3,5,7],size=(3,4))
print(r)

[[5 7 3 3]
 [5 7 7 3]
 [7 7 5 5]]


In [15]:
list1 = [1,2,3,4,5]
random.shuffle(list1)
print(list1)

[2, 5, 4, 1, 3]


In [16]:
tup1 = (1,2,3,4,5)
random.shuffle(tup1)
print(tup1)

TypeError: 'tuple' object does not support item assignment